export interface McpFunctionDef {
  name: string;
  domain: "o2c" | "p2p" | "r2r" | "h2r";
  description: string;
}

export const mcpCatalog: McpFunctionDef[] = [
  // ── O2C ──────────────────────────────────────────────────────────────────
  { name: "o2c_create_customer", domain: "o2c", description: "Create a customer in Draft state" },
  { name: "o2c_activate_customer", domain: "o2c", description: "Activate a Draft customer" },
  { name: "o2c_create_quote", domain: "o2c", description: "Create a sales quote in Draft state" },
  { name: "o2c_add_quote_line", domain: "o2c", description: "Add a line item to a quote" },
  { name: "o2c_send_quote", domain: "o2c", description: "Send a Draft quote to the customer" },
  { name: "o2c_accept_quote", domain: "o2c", description: "Accept a Sent quote" },
  { name: "o2c_reject_quote", domain: "o2c", description: "Reject a Draft or Sent quote" },
  { name: "o2c_expire_quote", domain: "o2c", description: "Mark a Sent quote as Expired" },
  { name: "o2c_convert_quote_to_order", domain: "o2c", description: "Convert an Accepted quote to a sales order" },
  { name: "o2c_confirm_order", domain: "o2c", description: "Confirm a Draft sales order" },
  { name: "o2c_allocate_order", domain: "o2c", description: "Allocate stock for a Confirmed order" },
  { name: "o2c_ship_order", domain: "o2c", description: "Mark an Allocated order as Shipped" },
  { name: "o2c_close_order", domain: "o2c", description: "Close a Shipped order" },
  { name: "o2c_cancel_order", domain: "o2c", description: "Cancel a sales order" },
  { name: "o2c_generate_invoice", domain: "o2c", description: "Generate an AR invoice from a Shipped order" },
  { name: "o2c_create_shipment", domain: "o2c", description: "Create shipment for a Confirmed or Allocated order" },
  { name: "o2c_execute_shipment", domain: "o2c", description: "Mark a Planned shipment as Shipped" },
  { name: "o2c_deliver_shipment", domain: "o2c", description: "Mark a Shipped shipment as Delivered" },
  { name: "o2c_cancel_shipment", domain: "o2c", description: "Cancel a shipment" },
  { name: "o2c_post_ar_invoice", domain: "o2c", description: "Post a Draft AR invoice" },
  { name: "o2c_cancel_ar_invoice", domain: "o2c", description: "Cancel an AR invoice" },
  { name: "o2c_register_payment", domain: "o2c", description: "Register an AR payment receipt" },
  { name: "o2c_apply_ar_payment", domain: "o2c", description: "Apply a Received AR payment to an invoice" },
  { name: "o2c_reconcile_ar_payment", domain: "o2c", description: "Reconcile an Applied AR payment" },
  { name: "o2c_cancel_ar_payment", domain: "o2c", description: "Cancel an AR payment" },

  // ── P2P ──────────────────────────────────────────────────────────────────
  { name: "p2p_create_requisition", domain: "p2p", description: "Create a purchase requisition in Draft state" },
  { name: "p2p_submit_requisition", domain: "p2p", description: "Submit a Draft requisition for approval" },
  { name: "p2p_approve_requisition", domain: "p2p", description: "Approve a Submitted requisition" },
  { name: "p2p_reject_requisition", domain: "p2p", description: "Reject a Submitted requisition" },
  { name: "p2p_cancel_requisition", domain: "p2p", description: "Cancel a Draft or Submitted requisition" },
  { name: "p2p_convert_requisition_to_po", domain: "p2p", description: "Convert an Approved requisition to a PO" },
  { name: "p2p_create_supplier", domain: "p2p", description: "Create a supplier in Draft state" },
  { name: "p2p_activate_supplier", domain: "p2p", description: "Activate a Draft supplier" },
  { name: "p2p_suspend_supplier", domain: "p2p", description: "Suspend an Active supplier" },
  { name: "p2p_create_po", domain: "p2p", description: "Create a purchase order in Draft state" },
  { name: "p2p_approve_po", domain: "p2p", description: "Approve a Draft purchase order" },
  { name: "p2p_send_po", domain: "p2p", description: "Send an Approved purchase order to the supplier" },
  { name: "p2p_receive_goods_on_po", domain: "p2p", description: "Record goods receipt against a Sent PO" },
  { name: "p2p_close_po", domain: "p2p", description: "Close a fully received purchase order" },
  { name: "p2p_cancel_po", domain: "p2p", description: "Cancel a purchase order" },
  { name: "p2p_create_goods_receipt", domain: "p2p", description: "Create a goods receipt from a Sent/PartiallyReceived PO" },
  { name: "p2p_goods_receipt_receive", domain: "p2p", description: "Mark goods receipt as Received" },
  { name: "p2p_goods_receipt_accept", domain: "p2p", description: "Accept a Received goods receipt" },
  { name: "p2p_create_supplier_invoice", domain: "p2p", description: "Create a supplier invoice from an Accepted receipt" },
  { name: "p2p_validate_invoice", domain: "p2p", description: "Validate a Draft supplier invoice" },
  { name: "p2p_post_supplier_invoice", domain: "p2p", description: "Post a Validated supplier invoice" },
  { name: "p2p_cancel_invoice", domain: "p2p", description: "Cancel a supplier invoice" },
  { name: "p2p_create_ap_payment", domain: "p2p", description: "Create an AP payment in Draft state" },
  { name: "p2p_receive_ap_payment", domain: "p2p", description: "Mark an AP payment as Received" },
  { name: "p2p_apply_ap_payment", domain: "p2p", description: "Apply a Received AP payment to an invoice" },
  { name: "p2p_reconcile_ap_payment", domain: "p2p", description: "Reconcile an Applied AP payment" },
  { name: "p2p_cancel_ap_payment", domain: "p2p", description: "Cancel an AP payment" },

  // ── R2R ──────────────────────────────────────────────────────────────────
  { name: "r2r_create_ledger", domain: "r2r", description: "Create a general ledger" },
  { name: "r2r_create_account", domain: "r2r", description: "Create a chart of accounts entry" },
  { name: "r2r_create_fiscal_year", domain: "r2r", description: "Create a fiscal year in Open state" },
  { name: "r2r_start_year_close", domain: "r2r", description: "Place a fiscal year in Closing state" },
  { name: "r2r_close_fiscal_year", domain: "r2r", description: "Close a fiscal year" },
  { name: "r2r_create_fiscal_period", domain: "r2r", description: "Create a fiscal period in Open state" },
  { name: "r2r_start_period_close", domain: "r2r", description: "Place a fiscal period in Closing state" },
  { name: "r2r_close_fiscal_period", domain: "r2r", description: "Close a fiscal period" },
  { name: "r2r_lock_fiscal_period", domain: "r2r", description: "Lock a Closed fiscal period" },
  { name: "r2r_create_manual_journal", domain: "r2r", description: "Create a journal in Draft state" },
  { name: "r2r_add_journal_line", domain: "r2r", description: "Add a debit/credit line to a journal" },
  { name: "r2r_post_journal", domain: "r2r", description: "Post a Draft journal" },
  { name: "r2r_reverse_journal", domain: "r2r", description: "Reverse a Posted journal" },
  { name: "r2r_cancel_journal", domain: "r2r", description: "Cancel a Draft journal" },
  { name: "r2r_get_trial_balance", domain: "r2r", description: "Get trial balance for a fiscal period" },

  // ── H2R ──────────────────────────────────────────────────────────────────
  { name: "h2r_create_employee", domain: "h2r", description: "Create an employee in Candidate state" },
  { name: "h2r_activate_employee", domain: "h2r", description: "Activate a Candidate employee" },
  { name: "h2r_place_on_leave", domain: "h2r", description: "Place an Active employee on leave" },
  { name: "h2r_return_from_leave", domain: "h2r", description: "Return an OnLeave employee to Active" },
  { name: "h2r_terminate_employee", domain: "h2r", description: "Terminate an employee" },
  { name: "h2r_create_position", domain: "h2r", description: "Create a position with authority tier" },
  { name: "h2r_create_assignment", domain: "h2r", description: "Create an assignment in Planned state" },
  { name: "h2r_activate_assignment", domain: "h2r", description: "Activate a Planned assignment" },
  { name: "h2r_complete_assignment", domain: "h2r", description: "Complete an Active assignment" },
  { name: "h2r_cancel_assignment", domain: "h2r", description: "Cancel an assignment" },
  { name: "h2r_end_assignment", domain: "h2r", description: "End an assignment (alias for complete)" },
  { name: "h2r_issue_credential", domain: "h2r", description: "Issue a credential in Valid status" },
  { name: "h2r_expire_credential", domain: "h2r", description: "Expire a Valid credential" },
  { name: "h2r_revoke_credential", domain: "h2r", description: "Revoke a Valid credential" },
  { name: "h2r_create_authority_rule", domain: "h2r", description: "Create an authority approval rule" }
];
