import { McpFunctionDef } from "./catalog";

export const p2pFunctions: McpFunctionDef[] = [
  { name: "p2p_create_requisition", domain: "p2p", description: "Create requisition" },
  { name: "p2p_add_requisition_line", domain: "p2p", description: "Add requisition line" },
  { name: "p2p_update_requisition_line", domain: "p2p", description: "Update requisition line" },
  { name: "p2p_remove_requisition_line", domain: "p2p", description: "Remove requisition line" },
  { name: "p2p_submit_requisition", domain: "p2p", description: "Submit requisition" },
  { name: "p2p_approve_requisition", domain: "p2p", description: "Approve requisition" },
  { name: "p2p_reject_requisition", domain: "p2p", description: "Reject requisition" },
  { name: "p2p_cancel_requisition", domain: "p2p", description: "Cancel requisition" },
  { name: "p2p_convert_requisition_to_po", domain: "p2p", description: "Convert requisition to PO" },
  { name: "p2p_create_supplier", domain: "p2p", description: "Create supplier" },
  { name: "p2p_activate_supplier", domain: "p2p", description: "Activate supplier" },
  { name: "p2p_suspend_supplier", domain: "p2p", description: "Suspend supplier" },
  { name: "p2p_create_po", domain: "p2p", description: "Create purchase order" },
  { name: "p2p_add_po_line", domain: "p2p", description: "Add purchase order line" },
  { name: "p2p_update_po_line", domain: "p2p", description: "Update purchase order line" },
  { name: "p2p_remove_po_line", domain: "p2p", description: "Remove purchase order line" },
  { name: "p2p_approve_po", domain: "p2p", description: "Approve purchase order" },
  { name: "p2p_send_po", domain: "p2p", description: "Send purchase order to supplier" },
  { name: "p2p_receive_goods_on_po", domain: "p2p", description: "Record goods receipt on PO" },
  { name: "p2p_close_po", domain: "p2p", description: "Close purchase order" },
  { name: "p2p_cancel_po", domain: "p2p", description: "Cancel purchase order" },
  { name: "p2p_create_goods_receipt", domain: "p2p", description: "Create goods receipt" },
  { name: "p2p_goods_receipt_receive", domain: "p2p", description: "Receive goods" },
  { name: "p2p_goods_receipt_accept", domain: "p2p", description: "Accept received goods" },
  { name: "p2p_create_supplier_invoice", domain: "p2p", description: "Create supplier invoice" },
  { name: "p2p_validate_invoice", domain: "p2p", description: "Validate supplier invoice" },
  { name: "p2p_post_supplier_invoice", domain: "p2p", description: "Post supplier invoice" },
  { name: "p2p_cancel_invoice", domain: "p2p", description: "Cancel supplier invoice" },
  { name: "p2p_create_ap_payment", domain: "p2p", description: "Create AP payment" },
  { name: "p2p_receive_ap_payment", domain: "p2p", description: "Receive AP payment" },
  { name: "p2p_apply_ap_payment", domain: "p2p", description: "Apply AP payment" },
  { name: "p2p_reconcile_ap_payment", domain: "p2p", description: "Reconcile AP payment" },
  { name: "p2p_cancel_ap_payment", domain: "p2p", description: "Cancel AP payment" }
];
